### ISSUE TITLE
Installing NuGet package doesn't add Novicell.Examine.ElasticSearch.dll to bin folder

### ISSUE THREAD

**Issue by inetzo** [Novicell/Novicell.Examine.ElasticSearch#13]
Hi @bielu ,

I've installed both Novicell.Examine.ElasticSearch and Novicell.Examine.ElasticSearch.Umbraco via NuGet but it doesn't add the assemblies

![afbeelding](https://user-images.githubusercontent.com/18665536/102665340-037e5980-4185-11eb-9f53-9d4b4daed81d.png)

They are not in the bin-folder. Do I am missing another nessecerly package?
Best regards,

iNETZO

**Comment by bielu** [comment]
Hi @inetzo,
Just checked looks like I made mistake in time of cleaning of nuspecs for nuget and I removed by incident files from nuget package, I fixed that in version 1.0.0-Beta.2935, thanks for reporting!
Please confirm if everything works in newest package and I will close ticket then.

**Comment by inetzo** [comment]
Hi @bielu ,
Thank you very much for updating your NuGet package! The assemblies do get properly installed now.
But unfortunately the search in the backoffice doesn't work. I've used the standard Umbraco Starterkit (Umbraco 8.9.1).
In Kibana I now see some temp-indexes with documents in them but the indexes with date in them seem to be empty.

![afbeelding](https://user-images.githubusercontent.com/18665536/102723218-dbb6ff00-4306-11eb-9b26-bab8f28df900.png)

**Comment by bielu** [comment]
@inetzo I will need check that with 8.8 and 8.9 as there were some changes in Examine(implemenation in umbraco), I am closing that ticket, can you create new one about issues with indexing :)?

**Comment by inetzo** [comment]
I couldn't replicate this issue so i guess something else caused the temp index problem.
