### ISSUE TITLE
TransformingIndexValue is not fired after installing Novicell.Examine.ElasticSearch.Umbraco

### ISSUE THREAD

**Issue by inetzo** [Novicell/Novicell.Examine.ElasticSearch#14]
Hi,

After installing the Novicell.Examine.ElasticSearch.Umbraco package, the TransformingIndexValue is not fired anymore.
I tried to run the composer after the ElasticSearchExamineComposer but it still doesn't fire when reindexing.
When i remove Novicell.Examine.ElasticSearch.Umbraco the event gets fired (but than running with Lucene of course).

I tried it using the Umbraco Startkit with Umbraco 8.6.4 with Examine 1.0.6 and Novicell.Examine.ElasticSearch.Umbraco 1.0.0-Beta.2935.

```
using Examine;
using Examine.Providers;
using Novicell.Examine.ElasticSearch.Umbraco;
using System;
using System.Text;
using Umbraco.Core;
using Umbraco.Core.Composing;
using Umbraco.Core.Scoping;
using Umbraco.Examine;
using Umbraco.Web;

namespace UmbracoElasticSearch.ElasticSearch
{
    [RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    [ComposeAfter(typeof(ElasticSearchExamineComposer))]
    public class ExamineComposer : ComponentComposer<ExamineEvents>, IUserComposer
    {
    }

    public class ExamineEvents : IComponent
    {
        private readonly IExamineManager _examineManager;
        private readonly IUmbracoContextFactory _umbracoContextFactory;
        private readonly IScopeProvider _scopeProvider;

        public ExamineEvents(IExamineManager examineManager, IUmbracoContextFactory umbracoContextFactory, IScopeProvider scopeProvider)
        {
            _examineManager = examineManager;
            _umbracoContextFactory = umbracoContextFactory;
            _scopeProvider = scopeProvider;
        }

        public void Initialize()
        {
            if (!_examineManager.TryGetIndex(Constants.UmbracoIndexes.ExternalIndexName, out IIndex index))
                throw new InvalidOperationException($"No index found by name {Constants.UmbracoIndexes.ExternalIndexName}");

            //we need to cast because BaseIndexProvider contains the TransformingIndexValues event
            if (!(index is BaseIndexProvider indexProvider))
                throw new InvalidOperationException("Could not cast");

            indexProvider.TransformingIndexValues += IndexProviderTransformingIndexValues;
        }

        private void IndexProviderTransformingIndexValues(object sender, IndexingItemEventArgs e)
        {
            if (e.ValueSet.Category == IndexTypes.Content)
            {
                var combinedFields = new StringBuilder();

                foreach (var fieldValues in e.ValueSet.Values)
                {
                    foreach (var value in fieldValues.Value)
                    {
                        if (value != null)
                        {
                            combinedFields.AppendLine(value.ToString());
                        }
                    }
                }

                //Accessing the Umbraco Cache code will be added in the next step.
                //combinedFields.AppendLine(GetBreadcrumb(e.ValueSet.Values["id"].FirstOrDefault()?.ToString()));

                e.ValueSet.TryAdd("combinedField", combinedFields.ToString());


            }
        }

        public void Terminate()
        {
            //unsubscribe during shutdown
        }
    }
}
```

**Comment by bielu** [comment]
HI @inetzo,
can you maybe try that on Umbraco 8.9.1 and 1.0.0-Beta.2940(It should be available on nuget in few minutes)? 
As in 1.0.0-Beta.2940 I added that event as I noticed I never implement calling that event.

**Comment by inetzo** [comment]
Hi @bielu , 
Thank you very much for picking up this issue quickly, I really appreciate that.
I can confirm that the TransformingIndexValues event is now being picked up again and that the values are indexed properly.

We use Umbraco 8.6.4 for our main project. It's for the moment complicated to update it to 8.9.1.
Is there a dependency reason that new betaversions need Umbraco 8.9.1?

Thanks again and kind regards,
iNETZO

**Comment by bielu** [comment]
@inetzo breaking change in 8.9.1 :) which is not documented as always... 👎

**Comment by bielu** [comment]
As Issue was resolved I am closing that ticket :). about backporting to lower version, you can always check that commit:
https://github.com/Novicell/Novicell.Examine.ElasticSearch/commit/75b1aa86e04627557dec538cbd4c0c9f829fcb44
and backport that to lower version and built custom version and use that as long you will need :)

**Comment by inetzo** [comment]
We've backported it succesfully to the source of 2935. The right version of ElasticSearch-Inside package was missing but we've used https://www.nuget.org/packages/elasticsearch-inside/6.6.1 and it still works.
Thanks again for your help!
