### ISSUE TITLE
Is Novicell.Examine.ElasticSearch compatible with Umbraco v7.14?

### ISSUE THREAD

**Issue by jaeyow** [Novicell/Novicell.Examine.ElasticSearch#20]
I would like to use ElasticSearch instead of the out of the box Examine, however I am using Umbraco v7.14. Not clear in the documentation if this version is supported. 

Before I try to go through the whole process, I wanted to ask first if this is expected to work in this version, or I shouldn't bother at all as there is no support for it?

Thanks

**Comment by jaeyow** [comment]
Having read this https://www.novicell.co.uk/blog/elastic-all-the-things/ it looks like this only support > v8.

**Comment by bielu** [comment]
@jaeyow v7 can't be supported because of infrastructure of examine in umbraco v7.

**Comment by jaeyow** [comment]
thanks @bielu
