### ISSUE TITLE
Is Novicell.Examine.ElasticSearch compatible with Umbraco >8.6 ?

### ISSUE THREAD

**Issue by inetzo** [Novicell/Novicell.Examine.ElasticSearch#8]
Hi,

After having problems again with Lucene, i realy like to try your solution for replacing it with ElasticSearch.
Unfortunately I can't get it working with Umbraco 8.6.3. When I do a fresh install of Umbraco with startkit and follow the steps from the wiki and then start Umbraco under Settings, "Examine Management" the default Lucene indexes remain active instead of the ElasticSearch indexes.

Is this project suitable for> Umbraco 8.6?

Best regards,

iNETZO

**Comment by inetzo** [comment]
Instead of using NuGet, I've now downloaded the package from our.umbraco.com (Novicell.Examine.ElasticSearch.Umbraco_1.0.0-alpha-000105) and now the indexing in Elastic works!

**Comment by bielu** [comment]
@inetzo I will check package why it didn't work on 8.6.3, can you share maybe your error logs as from that what I know 8.4+ didnt change anything about examine index, also really soon I am going to release new version which will introduce new features and hopefully it will be first non alpha/beta version as Umbraco stop making in examine integration :)

**Comment by inetzo** [comment]
Hi @bielu , my problem was that there was no Nuget-package for Novicell.Examine.ElasticSearch.Umbraco that would install. So i downloaded the zip from Our Umbraco and know it works very well! Is there documentation how i can convert my custom indexes to Elastic?

**Comment by bielu** [comment]
@inetzo we have nuget package but it is prelease still :) and I would still recommend use prelease nuget version, about documentation I didn't prepare that yet but ways is almot same as in umbraco but you need use "ContentElasticSearchIndex" and you can look here:
https://github.com/Novicell/Novicell.Examine.ElasticSearch/blob/8a33ecaf434f9fc8b77960c1190f5fa9a868cde2/source/Novicell.Examine.ElasticSearch.Umbraco/ElasticIndexCreator.cs#L49
